### ISSUE TITLE
implement Grafana and Prometheus for monitoring

### ISSUE THREAD

**Issue by vaibhavyadav-dev** [BharatSeva/BharatSeva-Plus-Express-Server#1]
## Issue Description
We need to implement monitoring for Express server using Grafana and Prometheus. 

### Prometheus Setup:
- Install and configure Prometheus on the server.
- Set up Prometheus configuration to scrape metrics from the application, services, and system.
- Define scrape intervals and targets (e.g., Node Exporter, Application metrics, etc.).

### Grafana Setup:
- Install and configure Grafana on the server.
- Connect Grafana to the Prometheus data source.
- Create dashboards for system metrics (CPU, memory, disk usage will be enough) and application metrics.

### Integrate with the Application:
- Ensure the application exposes metrics for Prometheus to scrape (e.g., using libraries like prom-client in Node.js)
---
### Documentation:
- Add documentation on how to access Prometheus and Grafana.

**Comment by uchiha-vivek** [comment]
@vaibhavyadav-dev  sir I want to work on this issue. I will share my step by step progress here. Please assign me this issue.

**Comment by vaibhavyadav-dev** [comment]
Great @uchiha-vivek , go ahead and make sure you've read the contribution guidelines. 
If run into any issue you can drop your message and I'll help you out.

**Comment by uchiha-vivek** [comment]
@vaibhavyadav-dev  sure

**Comment by vaibhavyadav-dev** [comment]
@uchiha-vivek any update ?

**Comment by uchiha-vivek** [comment]
Yes sir I m working on it @vaibhavyadav-dev

**Comment by uchiha-vivek** [comment]
@vaibhavyadav-dev  Sir we will also need one docker file , i m almost done with it

**Comment by vaibhavyadav-dev** [comment]
Sure @uchiha-vivek

**Comment by uchiha-vivek** [comment]
@vaibhavyadav-dev  Sir i have raised the pull request , please let me know if some corrections need to be made.

**Comment by vaibhavyadav-dev** [comment]
DONE
