### ISSUE TITLE
Improvement in UI of login/signup page 

### ISSUE THREAD

**Issue by rohitja26** [BharatSeva/BharatSeva-Plus-Express-Server#10]
The UI of the signup/login page is very worst and need to be improved. I can help you with that by improving the UI of the signup page

**Comment by vaibhavyadav-dev** [comment]
@rohitja26 this is express server, if you want to contribute to UI [Visit here](https://github.com/BharatSeva/BharatSeva-Plus-User-Interface)
THIS IS NOT FRONTEND OF PROJECT. Please don't spam issue section with such things.
