### ISSUE TITLE
Include CODE_OF_CONDUCT file 

### ISSUE THREAD

**Issue by pratyush090506** [BharatSeva/BharatSeva-Plus-Express-Server#3]
I'd like to update the repository with the CODE_OF_CONDUCT file.

Can you please assign this task to me?

**Comment by vaibhavyadav-dev** [comment]
@pratyush090506 it'd be great if you can contribute to documentation of this project.
I can help you with it.

**Comment by acenasir** [comment]
Can you please assign this task to me? @pratyush090506
