### ISSUE TITLE
improve homepage and about section

### ISSUE THREAD

**Issue by Vardhan-Harsh07** [BharatSeva/BharatSeva-Plus-Express-Server#4]
![image](https://github.com/user-attachments/assets/9adb7673-1df2-4299-9dec-a5993b193003)
![image](https://github.com/user-attachments/assets/9eff205c-9dfc-42b2-8138-5b5a9b35c3d4)
the ui of homepage needs to be changed and make it pleasant for the viewers well i can improve its frontend u can assign it to me thanks !!

**Comment by vaibhavyadav-dev** [comment]
@Vardhan-Harsh07 this is backend, create this issue [here](https://github.com/BharatSeva/BharatSeva-Plus-User-Interface) and I'll assign you.
