### ISSUE TITLE
Enhancement: Separation of User Functionality

### ISSUE THREAD

**Issue by vaibhavyadav-dev** [BharatSeva/BharatSeva-Plus-Express-Server#5]
### Description
Currently, the Bharat Seva+ project has both healthcare and user functionalities tightly coupled in the same service. To improve modularity, maintainability, and scalability, we need to decouple the user functionality and build it as a separate service. This will allow independent development, deployment, and scaling of the user and healthcare functionalities.

### Proposal
   - Move all user-related code and logic (authentication, user profile management, etc.) from the current service into a new microservice dedicated to handling user-related functionality.

### Key Benefits
- **Improved Scalability**: User and healthcare functionalities can be scaled independently.
- **Better Maintainability**: Code for each functionality is isolated, making it easier to modify or enhance without impacting the other.
- **Clear Separation of Concerns**: The healthcare and user management services will be more focused, leading to a more organized codebase.

### Tasks
1. Refactor and remove user-related logic from the current healthcare service.
2. Set up a new server that manages user (Patient) request only, microservice for user-related functionality.
3. Build in Golang (Preferable) or JavaScript.
4. Test the service.

### Additional Notes
- We do not need to make separate APIs endpoints for user just use the current API endpoints.
- If written in Golang, use frameworks like Echo (Preferable) or Gin for the user API.
- Make Documentation.

### Expected Outcome
By the end of this task, the BharatSeva+ platform should have a decoupled architecture with a separate service for user management.

**Comment by ApurvaBasule** [comment]
hii @vaibhavyadav-dev i would like to take upon it could you please assign it to me

**Comment by vaibhavyadav-dev** [comment]
Hello @ApurvaBasule Thank you for your interest in taking on this issue. Before you proceed, could you please share your plan on how you intend to approach this task? 
Let’s align on the approach before you begin working.

**Comment by ApurvaBasule** [comment]
I apologize for the late response @vaibhavyadav-dev I've been busy with my college submission...I'm planning to proceed with setting up the user microservice as discussed..My approach will involve creating a new Express server,Once I have everything set up and verified that it works smoothly, I will document the microservice architecture and deployment steps to provide a clear overview of the changes made and I'll keep you updated on my progress!

**Comment by vaibhavyadav-dev** [comment]
@ApurvaBasule are you still working on this issue ? It's been a week now and task is not that level. 
All you've to do is just use the user functionality and remove the healthcare care one 
[Healthcare](https://github.com/BharatSeva/Healthcare-Server) has been created and there's no reply from your side

**Comment by vaibhavyadav-dev** [comment]
[User Server](https://github.com/BharatSeva/User-Server) Completed
