### ISSUE TITLE
adding dark mode toggle feature to the HTML file organizing the html code to a understandable format

### ISSUE THREAD

**Issue by bitbroke** [BharatSeva/BharatSeva-Plus-Express-Server#6]
many  users prefer dark mode everywhere , this feature will enhance user experience 
your html code is written in a single line making it weird to read , by working on this issue i would like to make ur html file better too .

**Comment by bitbroke** [comment]
please assign this issue to me under hacktoberfest2024

**Comment by vaibhavyadav-dev** [comment]
@bitbroke this is backend of this project [visit here](https://github.com/BharatSeva/BharatSeva-Plus-User-Interface) to raise issue, get assigned and start working.
