### ISSUE TITLE
Include CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by PragyaTripathi990** [BharatSeva/BharatSeva-Plus-Express-Server#8]
I would like to add CODE_OF_CONDUCT file in your repository.

 Could you please assign me this issue ?

**Comment by vaibhavyadav-dev** [comment]
@PragyaTripathi990 don't you see someone already raised this issue ?

**Comment by vaibhavyadav-dev** [comment]
PLEASE DON'T CREATE ISSUE FOR SUCH CHEAP TASK.
You're capable of more than you think, creating or even thinking such unwanted things will not help you in long run. I request everyone don't come here if you want to increase your PR count.
